config/routes.rb
PollingApp::Application.routes.draw do
  resources :polls do
    resources :items do 
      member do 
        put :vote_up
      end
    end
  end

  root 'polls#index'

  

end

app/models/ip_list.rb
class IpList < ActiveRecord::Base
  belongs_to :poll
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :poll

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  validates_presence_of :title
  validate :require_two_items, :max_five_items

  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  has_many :ip_lists
  
  private
    def require_two_items
      errors.add(:base, "You must provide at least two items") if items.size < 2
    end

    def max_five_items
      errors.add(:base, "You have exceeded the maximum items of five") if items.size > 5
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 

  def current_ip
    request.remote_ip
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :check_ip, only: :vote_up

  def vote_up
    poll = Poll.find(params[:poll_id])
    item = poll.items.find(params[:id])
    
    item.increment!(:votes)
    poll.ip_lists.create(ip_address: current_ip) unless poll.ip_lists.find_by_ip_address(current_ip)

    redirect_to poll_path(poll), notice: 'Your vote was successfully recorded.'
  end

  protected 
    def check_ip
      poll = Poll.find(params[:poll_id])
      if poll.ip_lists.find_by_ip_address(current_ip)
        redirect_to poll_path(poll), alert: "You've already voted."
      end        
    end
  
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_filter :vote_casted?, only: [:edit, :update]
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render action: 'show', status: :created, location: @poll }
      else
        format.html { render action: 'new' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end

  protected

    def vote_casted?
      poll = Poll.find(params[:id])
      #check if poll has any votes
      votes = poll.items.collect(&:votes).uniq 
      if votes.max > 0 
        redirect_to poll_path(poll), alert: "You cannot edit the poll because someone has already voted on it."   
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title, items_attributes: [:id, :title, :vote, :poll_id, :_destroy])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/_flash.html.erb
<% unless notice.nil? %>
  <div class="bs-alerts-right-fix">
      <p class="alert alert-success">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      </p>
  </div>
<% end %>
<% unless alert.nil? %>
  <div class="bs-alerts-right-fix">
      <p class="alert alert-danger">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      </p>    
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PollingApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">PollingApp</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Polls", polls_path  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <!-- <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div> -->

        <div class="span9">
          <%= render 'layouts/flash' %>
          <%= yield %>
        </div>
      </div><!--/row-->


      <hr class="invisible">
      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/polls/_form.html.erb
<% if @poll.errors.any? %>
  <ul>
    <% @poll.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group field">
    <%= f.label :title, "Question", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div id="items">
    <%= f.fields_for :items do |item| %>
        <%= render 'item_fields', :f => item %> 
    <% end %>
    <div class="links">
      <%= link_to_add_association "Add Item", f, :items, partial: 'item_fields' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/_item_fields.erb
<div class="controls">
  <p>
    <div class="nested-fields">
      <div class="field">
        <%= f.label :title, "Item Title" %><br />
        <%= f.text_field :title %><br />
        <%= link_to_remove_association "Remove Item", f %>
      </div>
    </div>
  </p>
</div>

app/views/polls/edit.html.erb
<%- model_class = @poll.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/polls/index.html.erb
<%- model_class = Poll.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title)%></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.id, poll_path(poll) %></td>
        <td><%= link_to poll.title, poll_path(poll) %></td>
        <td><%=l poll.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_poll_path(poll), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poll_path(poll),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_poll_path,
            :class => 'btn btn-primary' %>

app/views/polls/new.html.erb
<%- model_class = @poll.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/polls/show.html.erb
<%- model_class = @poll.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @poll.title %></dd>
</dl>

<ul>
  <% @poll.items.each do |item| %>
  <li>
    <%= item.title %>: 

    <% if @poll.ip_lists.find_by_ip_address(request.remote_ip) %>
      <%= item.votes || "0" %> votes 
    <% else %>
      <%= link_to "vote", vote_up_poll_item_path(@poll, item), :method => :put %>
    <% end %>
  </li><br />
  <% end %>
</ul>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_path(@poll), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_path(@poll),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>